version: '2'
services:
  db:
    image: mongo
  web:
    build: .
    command: node server.js
    volumes:
      - .:/MusicRoom
      - /MusicRoom/node_modules
    ports:
      - "4242:4242"
    depends_on:
      - db
